"""
Authentication Router

This module handles user authentication, registration, and token management.
It uses OAuth2 with Password Flow and JWT tokens to secure the application.
"""
from fastapi import APIRouter, HTTPException, Depends, Path, status
from pydantic import BaseModel
from sqlalchemy.orm import Session
from typing import Annotated
from databse import SessionLocal
from model import Users
from passlib.context import CryptContext
from datetime import datetime, timedelta, timezone
from jose import jwt, JWTError  # To handle JWT
from fastapi.security import OAuth2PasswordRequestForm, OAuth2PasswordBearer  # Use for Login form

import os
from dotenv import load_dotenv

load_dotenv()

# STEP 1: JWT Configuration - generated by: python -c "import secrets; print(secrets.token_hex(32))"
SECRET_KEY = os.getenv("SECRET_KEY") or "15e64c4102e7431f0fe1ea0772acf0ebe85b58d0007614b9ef79dfb005c549e6"
ALGORITHM = os.getenv("ALGORITHM") or "HS256"
ACCESS_TOKEN_EXPIRE_MINUTES = 30

if not SECRET_KEY:
    raise RuntimeError("SECRET_KEY is missing from the .env file.")

pwd_context = CryptContext(schemes=["bcrypt"], deprecated="auto")
router = APIRouter(prefix="/auth", tags=["auth"])
oauth2_bearer = OAuth2PasswordBearer(tokenUrl="auth/token")


def get_db():
    db = SessionLocal()
    try:
        yield db
    finally:
        db.close()


db_dependency = Annotated[Session, Depends(get_db)]


# --- Schemas ---
class UserRequest(BaseModel):
    username: str
    password: str


class UserResponse(BaseModel):
    id: int
    username: str

    class Config:
        from_attributes = True


# 🛠️ STEP 2: Token Generate Function (Utility)
def create_access_token(username: str, user_id: int, role: str, expires_delta: timedelta):
    """
    Generate a JWT Access Token.

    Encodes user identity and role into a secure token with an expiration time.

    Args:
        username (str): The user's username (subject).
        user_id (int): The user's ID.
        role (str): The user's role (e.g., 'user', 'admin').
        expires_delta (timedelta): How long the token is valid for.

    Returns:
        str: Encoded JWT token string.
    """
    encode = {'sub': username, 'id': user_id, 'role': role}
    expires = datetime.now(timezone.utc) + expires_delta
    encode.update({'exp': expires})
    return jwt.encode(encode, SECRET_KEY, algorithm=ALGORITHM)

# check token and give user detail
async def get_current_user(token: Annotated[str, Depends(oauth2_bearer)]):
    """
    Validate Token and Retrieve Current User.

    Decodes the JWT token provided in the Authorization header.
    If valid, returns the user's details.

    Args:
        token (str): The OAuth2 token.

    Returns:
        dict: A dictionary containing username, id, and role.

    Raises:
        HTTPException: If token is invalid or user data is missing.
    """
    try:
        payload = jwt.decode(token, SECRET_KEY, algorithms=[ALGORITHM])
        username: str = payload.get("sub")
        user_id: int = payload.get("id")
        role: str = payload.get("role")
        if username is None or user_id is None:
            raise HTTPException(status_code=401, detail="User not validated")
        return {"username": username, "id": user_id, "role": role}
    except JWTError:
        raise HTTPException(status_code=401, detail="Token is invalid")


# 📝 STEP 3: User Creation (Signup)
@router.post("/", status_code=status.HTTP_201_CREATED)
async def create_user(db: db_dependency, user_request: UserRequest):
    """
    Register a New User.

    Creates a new user account if the username is unique.
    Hashes the password before storing it.

    Args:
        user_request (UserRequest): The payload containing username and password.

    Returns:
        dict: Success message.
    """
    existing_user = db.query(Users).filter(Users.username == user_request.username).first()
    if existing_user:
        raise HTTPException(status_code=400, detail="Username already registered")

    hashed_pass = pwd_context.hash(user_request.password)
    user_model = Users(username=user_request.username, hashed_password=hashed_pass)
    db.add(user_model)
    db.commit()
    return {"message": "User created successfully"}


# 🚪 STEP 4: Login Endpoint (Token Generation)
@router.post("/token")
async def login_for_access_token(
        form_data: Annotated[OAuth2PasswordRequestForm, Depends()],
        db: db_dependency
):
    """
    Authenticate User and Issue Token.

    Verifies username and password against the database.
    If successful, returns a JWT access token.

    Args:
        form_data (OAuth2PasswordRequestForm): Contains username and password.

    Returns:
        dict: Access token and token type.
    """
    # A. find User in database
    user = db.query(Users).filter(Users.username == form_data.username).first()

    # B. Check user found and password matching
    if not user or not pwd_context.verify(form_data.password, user.hashed_password):
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Invalid username or password"
        )

    # C. JWT Token generate
    token = create_access_token(
        user.username,
        user.id,
        user.role,
        timedelta(minutes=ACCESS_TOKEN_EXPIRE_MINUTES)
    )

    # D. Token return
    return {"access_token": token, "token_type": "bearer"}


@router.get("/", response_model=list[UserResponse])
async def get_all_users(db: db_dependency):
    """
    Retrieve All Users.

    Fetches a list of all registered users.
    
    Args:
        db (Session): Database session.

    Returns:
        list[UserResponse]: List of user objects.
    """
    return db.query(Users).all()